// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalWeb.Data;

#nullable disable

namespace PortalWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260311063103_CreateDocumentStructure")]
    partial class CreateDocumentStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalWeb.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Signer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PortalWeb.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7955),
                            Description = "Các công văn của tòa án",
                            DisplayOrder = 1,
                            Icon = "fa-file-alt",
                            IsActive = true,
                            Name = "Công văn"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7968),
                            Description = "Các thông báo chính thức",
                            DisplayOrder = 2,
                            Icon = "fa-bullhorn",
                            IsActive = true,
                            Name = "Thông báo"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7970),
                            Description = "Các nghị quyết của tòa án",
                            DisplayOrder = 3,
                            Icon = "fa-gavel",
                            IsActive = true,
                            Name = "Nghị quyết"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7971),
                            Description = "Các quyết định của tòa án",
                            DisplayOrder = 4,
                            Icon = "fa-clipboard",
                            IsActive = true,
                            Name = "Quyết định"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7973),
                            Description = "Các văn bản hướng dẫn",
                            DisplayOrder = 5,
                            Icon = "fa-compass",
                            IsActive = true,
                            Name = "Hướng dẫn"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7974),
                            Description = "Các biên bản họp, làm việc",
                            DisplayOrder = 6,
                            Icon = "fa-book",
                            IsActive = true,
                            Name = "Biên bản"
                        });
                });

            modelBuilder.Entity("PortalWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 11, 13, 31, 2, 638, DateTimeKind.Local).AddTicks(7263),
                            Email = "admin@toaan.gov.vn",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            Password = "$2a$11$S/Sf/D54wlvLHDQx0dB3wOEYKt9ATUT6VbYsdghdTFIk.RM1KoBRS",
                            Role = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PortalWeb.Models.Document", b =>
                {
                    b.HasOne("PortalWeb.Models.User", "Author")
                        .WithMany("Documents")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortalWeb.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("PortalWeb.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PortalWeb.Models.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
