// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalWeb.Data;

#nullable disable

namespace PortalWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260311055417_AddUserRelationships")]
    partial class AddUserRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(8301),
                            Description = "Các tin tức tổng hợp",
                            IsActive = true,
                            Name = "Tin tức",
                            Slug = "tin-tuc"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(8308),
                            Description = "Tin tức về công nghệ",
                            IsActive = true,
                            Name = "Công nghệ",
                            Slug = "cong-nghe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(8310),
                            Description = "Tin tức kinh doanh",
                            IsActive = true,
                            Name = "Kinh doanh",
                            Slug = "kinh-doanh"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(8311),
                            Description = "Tin tức thể thao",
                            IsActive = true,
                            Name = "Thể thao",
                            Slug = "the-thao"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(8313),
                            Description = "Tin tức giải trí",
                            IsActive = true,
                            Name = "Giải trí",
                            Slug = "giai-tri"
                        });
                });

            modelBuilder.Entity("PortalWeb.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PortalWeb.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("PortalWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 54, 16, 757, DateTimeKind.Local).AddTicks(7556),
                            Email = "admin@portal.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            Password = "$2a$11$542Wz1CIUC9BgJUCRPPchOzcIcgDWjApOoN2BrQT0dEpNuDZx8r3a",
                            Role = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PortalWeb.Models.Comment", b =>
                {
                    b.HasOne("PortalWeb.Models.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalWeb.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("News");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortalWeb.Models.News", b =>
                {
                    b.HasOne("PortalWeb.Models.User", "AuthorUser")
                        .WithMany("NewsArticles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortalWeb.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AuthorUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PortalWeb.Models.Category", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("PortalWeb.Models.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PortalWeb.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("NewsArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
